version: "3"

services:
  app:
    command: bash -c "source ./scripts/loadenv.sh && sleep infinity"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
